import { AppMap } from './types';

export const DEMO_APP_MAP: AppMap = {
  appName: 'FitFlow',
  appDescription: 'AI-powered fitness coaching app that creates personalized workout plans and tracks daily progress',
  appPlatform: 'mobile',
  journeys: [
    { id: 'j-onboarding', name: 'Onboarding', description: 'First-time user setup and personalized plan generation' },
    { id: 'j-training', name: 'Training', description: 'Daily workout generation and session tracking' },
    { id: 'j-insights', name: 'Insights', description: 'Progress analytics and AI coaching feedback' },
  ],
  moments: [
    {
      id: 'welcome',
      journeyId: 'j-onboarding',
      label: 'Welcome',
      type: 'ui',
      description: 'App splash and login/signup entry point with social auth options',
      preview: 'Dark splash screen with FitFlow logo, "Train smarter with AI" tagline, Sign Up and Log In buttons, Continue with Apple/Google options',
      position: { x: 0, y: 80 },
    },
    {
      id: 'fitness-assessment',
      journeyId: 'j-onboarding',
      label: 'Fitness Assessment',
      type: 'ui',
      description: 'User selects fitness level, goals, available workout days, and equipment',
      preview: 'Multi-step form: fitness level chips (Beginner/Intermediate/Advanced/Athlete), goal tags (Weight Loss/Muscle Gain/Endurance), 7-day grid picker for workout days, equipment checklist',
      position: { x: 320, y: 80 },
    },
    {
      id: 'ai-plan-gen',
      journeyId: 'j-onboarding',
      label: 'AI Plan Generation',
      type: 'ai',
      description: 'Claude analyzes user inputs and generates a personalized multi-week training plan with weekly schedule and milestones',
      preview: 'Animated AI thinking screen showing progress: "Analyzing your profile", "Building your schedule", "Generating workouts". Claude Sonnet badge. Estimated 8s wait.',
      position: { x: 640, y: 80 },
    },
    {
      id: 'plan-beginner',
      journeyId: 'j-onboarding',
      label: 'Beginner Plan',
      type: 'ui',
      description: '8-week foundation plan for beginners with 3-day full-body schedule',
      preview: 'Plan summary card: "8-Week Foundation" — 3 days/week, Full-body workouts, weekly milestones list, estimated calorie targets, Start Plan CTA button',
      position: { x: 960, y: -60 },
      branchOf: 'ai-plan-gen',
    },
    {
      id: 'plan-advanced',
      journeyId: 'j-onboarding',
      label: 'Advanced Plan',
      type: 'ui',
      description: '16-week elite plan for advanced users with 5-day Push/Pull/Legs split',
      preview: 'Plan summary card: "16-Week Elite" — 5 days/week, PPL split, periodisation model, competition simulation dates, performance benchmarks, Start Plan button',
      position: { x: 960, y: 220 },
      branchOf: 'ai-plan-gen',
    },
    {
      id: 'daily-workout',
      journeyId: 'j-training',
      label: 'Daily Workout',
      type: 'ui',
      description: "Today's workout screen with exercise list, sets/reps, rest timers, and completion tracking",
      preview: 'Workout header with day/muscle group. Exercise cards: name, sets × reps, rest time, weight input. Progress bar. "Start Workout" button. Est. 45 min badge.',
      position: { x: 1280, y: 80 },
    },
    {
      id: 'ai-workout',
      journeyId: 'j-training',
      label: 'AI Workout Adapt',
      type: 'ai',
      description: 'Claude adapts the workout in real-time based on energy level, recovery score, and available equipment',
      preview: 'Energy level slider 1–5, recovery score donut chart, equipment toggle chips. Submit shows adapted exercise list with Claude explanation note of what changed and why.',
      position: { x: 1280, y: 300 },
    },
    {
      id: 'progress',
      journeyId: 'j-insights',
      label: 'Progress Dashboard',
      type: 'ui',
      description: 'Weekly training stats, streak tracking, volume charts, and personal records',
      preview: 'Stats row: 12 Workouts, 87% Consistency, 3 PRs this week. Line chart of weekly volume. Recent PRs list. AI insights teaser card with "View Full Analysis" button.',
      position: { x: 1600, y: 80 },
    },
  ],
  edges: [
    { id: 'e1', source: 'welcome', target: 'fitness-assessment', label: 'Sign up' },
    { id: 'e2', source: 'fitness-assessment', target: 'ai-plan-gen', label: 'Submit' },
    { id: 'e3', source: 'ai-plan-gen', target: 'plan-beginner', label: 'Beginner' },
    { id: 'e4', source: 'ai-plan-gen', target: 'plan-advanced', label: 'Advanced' },
    { id: 'e5', source: 'plan-beginner', target: 'daily-workout', label: 'Start' },
    { id: 'e6', source: 'plan-advanced', target: 'daily-workout', label: 'Start' },
    { id: 'e7', source: 'daily-workout', target: 'ai-workout', label: 'Adapt' },
    { id: 'e8', source: 'daily-workout', target: 'progress', label: 'Complete' },
  ],
};
